<?php
$id = $_GET['id'];
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<!-- main section for Products  -->

<body>
    <h2>Add products using this form</h2>
    <?php
    echo $this->tag->form(["product/edit/?id=" . $id]);
    ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textfield([
            "pname", "placeholder" => "Product name",
            "class" => "form-control", "value" => $data['name']
        ]); ?>
    </p>
    <p>
        <label for="category">Category Name</label>
        <?php echo $this->tag->textfield([
            "pcategory", "placeholder" => "Category name",
            "class" => "form-control", "value" => $data['category']
        ]); ?>
    </p>
    <p>
        <label for="price">Price</label>
        <?php echo $this->tag->numericfield([
            "pprice", "placeholder" => "Price",
            "class" => "form-control", "value" => $data['price']
        ]); ?>
    </p>
    <p>
        <label for="stock">Stock</label>
        <?php echo $this->tag->numericfield([
            "pstock", "placeholder" => "Stock",
            "class" => "form-control", "value" => $data['stock']
        ]); ?>
    </p>

    <label for="Variations">Variations for Price</label>
    <?php echo $this->tag->numericfield([
        "price", "placeholder" => "Price",
        "class" => "form-control col-2 ", "value" => $data['attriprice']
    ]); ?>

    </p>
    <p>
        <?php echo $this->tag->submitButton(["update", 'class' => 'btn btn-primary']); ?>
    </p>

    <p>

        </form>
</body>

</html>

